INSERT INTO users (email, name, password) VALUES
('carlos.mendes@empresa.com', 'Carlos Mendes', 'hash123'),
('lucas.almeida@empresa.com', 'Lucas Almeida', 'hash123'),
('marina.costa@empresa.com', 'Marina Costa', 'hash123'),
('roberto.santos@empresa.com', 'Roberto Santos', 'hash123'),
('fernanda.lima@empresa.com', 'Fernanda Lima', 'hash123'),
('ana.souza@empresa.com', 'Ana Souza', 'hash123'),
('diego.alves@empresa.com', 'Diego Alves', 'hash123'),
('joao.ferreira@empresa.com', 'João Ferreira', 'hash123'),
('beatriz.rocha@empresa.com', 'Beatriz Rocha', 'hash123'),
('thiago.martins@empresa.com', 'Thiago Martins', 'hash123'),
('clara.silva@empresa.com', 'Clara Silva', 'hash123'),
('paulo.gomes@empresa.com', 'Paulo Gomes', 'hash123'),
('renata.nunes@empresa.com', 'Renata Nunes', 'hash123'),
('bruno.carvalho@empresa.com', 'Bruno Carvalho', 'hash123'),
('juliana.freitas@empresa.com', 'Juliana Freitas', 'hash123');